version: '3.8'
services:
  frontend:
    build: .
    ports:
      - "4200:4200"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development

  backend:
    build: ./api
    ports:
      - "8080:80"
